### ISSUE TITLE
create CSS colors and fonts

### ISSUE THREAD

**Issue by ABodey** [HappyBarScout/201-group-project#11]
A color pallet and font selection for all pages

**Comment by oscartzintzun** [comment]
Here are the colors;
{ FF 6666}, {FFAB66}, {52CDCD}, {5CE65C}
![5ce65c](https://cloud.githubusercontent.com/assets/17017476/24228682/032f05c0-0f33-11e7-80b3-196524e94a89.png)
![52cdcd](https://cloud.githubusercontent.com/assets/17017476/24228684/03333e74-0f33-11e7-957a-d12e42634e21.png)
![ff6666](https://cloud.githubusercontent.com/assets/17017476/24228683/0331314c-0f33-11e7-86b1-7a3c9da8dabb.png)
![ffab66](https://cloud.githubusercontent.com/assets/17017476/24228685/0333a206-0f33-11e7-9d82-e7bd8c01bc1d.png)

**Comment by oscartzintzun** [comment]
New colors : 
{3A3A3C}, {BADFB4}
Font: what Marcel used on the mock up website.
