### ISSUE TITLE
3 HTML

### ISSUE THREAD

**Issue by oscartzintzun** [HappyBarScout/201-group-project#2]
We need to create at least 3 different HTML files.  The less amount of pages doesn't necessarily mean better coding.  We need to have as many pages as we need to without having to cram everything in only 3 pages.

**Comment by oscartzintzun** [comment]
layout idea
![screenshot 35](https://cloud.githubusercontent.com/assets/17017476/24180801/4b63ef8c-0e74-11e7-92e9-79e1b567506e.png)

**Comment by Marcelw25** [comment]
finally done!!
