### ISSUE TITLE
Logo and Picture stock

### ISSUE THREAD

**Issue by ABodey** [HappyBarScout/201-group-project#9]
create a logo pic and other stock pictures

**Comment by Marcelw25** [comment]
![bs-home](https://cloud.githubusercontent.com/assets/14185871/24228429/69657b6e-0f31-11e7-8aea-2344075872e8.jpg)

**Comment by Marcelw25** [comment]
![bar-scout-concepts](https://cloud.githubusercontent.com/assets/14185871/24228441/8502ba6c-0f31-11e7-9fef-46acf6d3e3d5.jpg)

**Comment by Marcelw25** [comment]
![bs-home-no-logo](https://cloud.githubusercontent.com/assets/14185871/24318812/22c9bf14-10c9-11e7-8bf4-146737a4ac93.png)

Homepage background image without logo

**Comment by Marcelw25** [comment]
![bs-home-with-logo](https://cloud.githubusercontent.com/assets/14185871/24318825/56cee99c-10c9-11e7-9481-0b9b8e35ab03.png)

Background image with Bar Scout logo.

**Comment by Marcelw25** [comment]
![Uploading BS-logo (1).png…]()

**Comment by oscartzintzun** [comment]
![black-and-white-alcohol-bar-drinks](https://cloud.githubusercontent.com/assets/17017476/24325136/285257de-1150-11e7-9c66-82353ab12d1f.jpg)
![bookstorebar_bw_23](https://cloud.githubusercontent.com/assets/17017476/24325135/2851c2a6-1150-11e7-9449-558bb5273e38.jpg)
![portlandbarnightlife](https://cloud.githubusercontent.com/assets/17017476/24325137/285419de-1150-11e7-9c49-18a54e44415a.jpg)
